flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- exceptions-0.8.3
- mtl-2.2.1
- open-browser-0.2.1.0
- stm-2.4.4.1
- temporary-1.2.0.4
- text-1.2.2.1
- transformers-compat-0.5.1.4
resolver: ghc-8.0.1
